nome = input('Qual é seu nome? ')
print('Prazer em te conhecer', nome)
print('Qual sua data de Nascimento? ')
dia = input('Dia ')
mes = input('Mês ')
ano = input('Ano ')
print('Você Nasceu dia ', dia, 'de', mes, 'de', ano, 'Correto?')
num1 = input('Digite o primeiro número: ')
num2 = input('Digite o segundo número: ')
soma = int(num1) + int(num2)
print('O resultado da soma é: ' + str(soma))
